language: rust
cache: cargo

matrix:
  include:
    # OS compat
    - os: linux
    - os: osx

    # rustc version compat
    - rust: stable
    - rust: 1.41.0 # oldest supported version, keep in sync with README.md
    - rust: beta
    - rust: nightly

    # deployments
    - env: DEPLOY=1 TARGET=x86_64-apple-darwin OPENSSL_STATIC=yes
      script: cargo build --locked --release --target $TARGET
      os: osx
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl OPENSSL_DIR=$HOME/openssl-musl
      before_script: ./ci/travis-musl-openssl.sh
      script: cargo build --locked --release --target $TARGET
      addons:
        apt:
          packages:
          - musl-tools
  allow_failures:
    - rust: nightly

script:
  - cargo build --release --locked --verbose
  - RUST_BACKTRACE=1 cargo test --release --locked --all --verbose
  # Requires PR #321
  #- if [[ "${DIST_SCCACHE}" = "1" ]]; then RUST_BACKTRACE=1 cargo test --all --verbose test_dist_ -- --test-threads 1; fi

before_deploy:
  - "./ci/prep_deploy.sh"

deploy:
  api_key:
    secure: "rNku4C73zyGUHfXwoLjvfEBsqey48mJqb9Y7s4GzI3NpxT/SFhkxmcif89L+Hjbw9p6yQtmS6MuUrH3G2sMndbqPmm6QZYHfIUP1wqFBjJL2/A7B0Sf8eQweprUWqU/8DmRreC7Xe6Se0fYebQEyXVQurEy1SeUNsw9PVROBU630pimXwHDK1Kxj526cCXYGMeCrsEef/aJ9jkcvKIw88FIoO/VNYBe29at08rahsos6+O0jjQBL0rc1OlzkM1zVu/82CBd2/XcudJ4S+YZ0Y17SRnn5EhEgY9rYPq2bmLhbfyGYYHfhu5CIa2KC5g4AwJ0lDMh/Fa0+qHG0mVvVe34+b6X2+MvLswoUNxyC9lEYHSbkh+KEMgCMXQzMJULikn+S7ZHStYMLLKkQS+UPiekaP7aGKUk5wxz+ClWUH9ec19l+aBmcsoPLEM8dZBQcA9lCQBqC4/O9d3WOc+yARHhAnwilXyJeeH0CjYuerwt5mzRsB9/4LIJ58CzbhDEwlR6qQLb57qs3N5AwtGbQGWrgs0wLK06LGn3m5tEqBwb7WFPY9CtXxD9JP1IzLBbiJhrgdjSNDZ2oxgiP5Qi3fofQUoVKiUs8uWw8uZEzEvvwmHMs10Bt9mR4gt7/twsnucnrzUZlIjzN/rEv75Yf0JF89jylfZzq9AlpiP+pi+o="
  file_glob: true
  file: rblake2sum-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
